# Group Grades

## Grades [/api/grades/{year}]
All students have a central grades page on CATe for each year of completed/current study. This route exposes data on what modules were taken and what grades were received for said courses.

+ Parameters
  + year (number,`2013`) ... Year of study.

+ Model (application/json)

  [# {{{
    {
      course: {
        cid: "202",
        name: "Software Engineering - Algorithms",
        _link: "/api/courses/2013/202"
      },
      exercises: [
        {
          number: 1,
          type: "ESSAY",
          title: "Group Formation for CWs",
          setBy: "alw",
          declaration: {
            time: 1390780800000,
            version: 5
          }
          extension: 0,
          submission: {
            user: "lmj112",
            time: 1390611260430,
            version: 2
          },
          grade: "A+"
        }
      ]
    }
  ]# }}}

### Retrieve all Grades for Year [GET]
+ Request
  + Headers
    Authorization: Bearer TOKEN

+ Response 200
  
  [Grades][]

+ Response 401

